### ISSUE TITLE
Wrong configuration value for DCE field

### ISSUE THREAD

**Issue by Oktopuce** [a-r-m-i-n/dce#130]
**Versions**
- DCE version: **3.2.2**
- TYPO3 version: **12.4.20**
- PHP version: **8.2**

**Describe the bug**
If you try to create a new field in a DCE element or edit an existing DCE field, the **configuration**  field has always the value {value} instead of the real configuration value from variable.

![Screenshot-8](https://github.com/user-attachments/assets/06ac1636-aa2e-453d-9e8d-966fb62b0a16)

I found where it comes from, it's because of the style in **dce/Resources/Private/Templates/DceUserFields/Codemirror.html**

```
<div id="dceConfigurationWizard">
   ...
   <style>
	   textarea#dce-code-editor-{uniqueIdentifier} {
   		font-family: "Source Code Pro", "Courier New", monospace;
		   font-weight: bold;
	   }
   </style>
</div>
```

if this style bloc is set at the beginning instead of being inside `<div>`, everything works well:

```
<style>
	textarea#dce-code-editor-{uniqueIdentifier} {
		font-family: "Source Code Pro", "Courier New", monospace;
		font-weight: bold;
	}
</style>

<div id="dceConfigurationWizard">
   ...
</div>
```

**Comment by a-r-m-i-n** [comment]
This might fix your problem, but the real problem is, that the Jit compiler is not enabled in your PHP environment, which is a requirement of TYPO3. See here: https://docs.typo3.org/m/typo3/tutorial-getting-started/main/en-us/SystemRequirements/Index.html#configure

To enable the Jit compiler, you need to add this, to the php.ini:
```
pcre.jit=1
```

I'm still merging your PR, because for any reason Fluid seems to be able to handle this, even without enabled Jit compiler. And it does not effect the stylings. 

However, to avoid other side effects in Fluid, you really should enable the Jit compiler.
