### ISSUE TITLE
Container > Detail stops working after first translated item.

### ISSUE THREAD

**Issue by Scopestyle** [a-r-m-i-n/dce#2]
Hi  @a-r-m-i-n , I'm asked to repost the bug report here, in Reference to the discussion in the Slack channel yesterday.
Please let me know if you need any more info to reproduce this error.

**Current setup:**

- Enable DCE container = True
- Hide other container items, when detail page is triggered = True
- Detailseite = True
- Slugs and Detail all setup according to DCE documentation

**Result:**

- All works in Default language
- Without Slugs the detail page works as expected
- First element in English works with Slugs enabled
- In English, after the first DCE, the detail stops working and shows all items in list view.

This is somehow related to the slugs, without the clean URLs the page renders normally.

Kind regards,

Erik

**Comment by a-r-m-i-n** [comment]
I can confirm this behaviour, with enabled routing enhancer and on a translated page.

**Comment by a-r-m-i-n** [comment]
@Scopestyle Could you please check if the commit fixes the issue for you?

**Comment by a-r-m-i-n** [comment]
As you already figured out, the container elements (except the first) have no language overlay set. Because of that, the uid is different and the _LOCALIZED_UID is missing.

I've fixed that manually in Container Factory and allowed the DceRepository->getInstance method to handle a custom tt_content row (respecting manually added _LOCALIZED_UID).

**Comment by Scopestyle** [comment]
Hi Armin, I can confirm that your fix solved the issue! 👍
