### ISSUE TITLE
Changing field of type section to element causes issues

### ISSUE THREAD

**Issue by TBschen** [a-r-m-i-n/dce#24]
**Versions**
- DCE version: **2.8.4**
- TYPO3 version: **11.5**
- PHP version: **7.3**

**Describe the bug**
I've had a DCE with a "section" field including 3 fields inside. I've then changed the section field to element.
However, the variable now was not available at all in frontend.
I then checked the database and it turns out that "section_fields" still had a value of 3.

After clearing this field, the variable was available again.

**Comment by a-r-m-i-n** [comment]
Hello @TBschen,
when you change the structure of a DCE, the existing structures in content-elements (pi_flexform) based on this DCE, are not affected. When you change the type of a field, the content-element values will not change, what can lead to exceptions because of unexpected values.

I think I can not help you here. You need to adjust the values of pi_flexform on your own. But you could write an upgrade wizard for this, like I did just recently in this commit https://github.com/a-r-m-i-n/dce/commit/a48d9643c7c3e6808846b9284e3f942e8d555a7c

Hope it helps. Good luck.
