### ISSUE TITLE
Invalid flex form data structure on field name "pi_flexform" with element "bild" in section container "container_bilder": Nesting inline elements in flex form sections is not allowed.

### ISSUE THREAD

**Issue by ghwaldo** [a-r-m-i-n/dce#5]
Hello Armin, thanx for your great work on DCE.

The error above occurs on TYPO3 10.4 when i try do use a DCE with
1. Normal Element named title
2. Sektion named bilder
3. in the section a FAL - Element bild

This seems to be somethin that leads to such nested elements that were working in earlier TYPO2 Versions like 7.x.

I don't have such deep knowledges in Flexforms. So, can you help ?!

Waldo

**Comment by a-r-m-i-n** [comment]
Inside of sections, FAL does not work. It never it, because each section entry has no unique identifier. However, because I do not encourage using sections (use DCE container instead) I've removed [this configuration snippet](https://github.com/a-r-m-i-n/dce/blob/2.4.1/Resources/Public/CodeSnippets/ConfigurationTemplates/12%20FAL/File%20Abstraction%20Layer%20(section%20use%20only).xml). With this you can select sys_files directly without using the sys_file_references, which are not supported by sections.
