### ISSUE TITLE
DCE container not having the possibility to get input from an editor

### ISSUE THREAD

**Issue by daUhradone** [a-r-m-i-n/dce#58]
I you use DCEs containers, very often the headline changes every time you use the container-DCE on a different place/page on the website.
Since it is usually a organic design block it is not so perfect to work with two DCEs. One on top and then the container.
It would be nice if an editor could also pipe input to the container head.

**Comment by a-r-m-i-n** [comment]
This is impossible because the container is not physically existing. What you could do is to add a new field for the container header, and access it in container template using `{dces.0.get.container_headline}`. This would use the contents of the first element in the container.

If you need physical containers, I recommend using EXT:container
