### ISSUE TITLE
Template files & browser are broken on typo3 >9

### ISSUE THREAD

**Issue by apttx** [a-r-m-i-n/dce#6]
Typo3 11.5.6 or 10.4.24 (migrated from 9.5.31)
PHP 7.4.27
DCE 2.8.1

Template file browser is missing and file URI inside a text field is displayed instead.

![image](https://user-images.githubusercontent.com/62893352/154308277-ca432aee-9b1d-4184-896d-04c8893ed040.png)

Even though a file is specified with correct syntax, it seems to not be resolved correctly which leads to no elements being rendered.

Workaround: switch to inline type & copy-paste file contents, inline templates work fine.

**Comment by a-r-m-i-n** [comment]
This link type is not supported anymore by DCE, because it is FAL related and template files should not be managed by FAL. Also this requires database queries being executed. Please use `EXT:` or absolute paths (e.g. `fileadmin/templates/...`) instead.

Because of this, the link wizard has been removed. Something which is wrong illustrated in current documentation: https://docs.typo3.org/p/t3/dce/main/en-us/UsersManual/Template.html#file
