### ISSUE TITLE
Using an image inside a section

### ISSUE THREAD

**Issue by vincentvega123** [a-r-m-i-n/dce#73]
In DCE 2.9.5 I used this to select a file inside a section:

```
<config>
	<type>group</type>
	<internal_type>db</internal_type>
	<appearance>
		<elementBrowserType>file</elementBrowserType>
		<elementBrowserAllowed>gif,jpg,jpeg,png</elementBrowserAllowed>
	</appearance>
	<allowed>sys_file</allowed>
	<size>1</size>
	<minitems>1</minitems>
	<maxitems>1</maxitems>
	<show_thumbs>1</show_thumbs>

	<dce_load_schema>1</dce_load_schema>
	<dce_get_fal_objects>1</dce_get_fal_objects>
</config>
```

In Version 3 this was changed by the updater script to

```
<config>
	<type>file</type>
	<minitems>1</minitems>
	<maxitems>1</maxitems>

	<dce_load_schema>1</dce_load_schema>
	<dce_get_fal_objects>1</dce_get_fal_objects>
</config>
```

When using this, an error message appears, when trying to edit the record:
Invalid flex form data structure on field name "pi_flexform" with element "image" in section container "container_slides": Nesting file elements in flex form sections is not allowed.

I know that inside the sections it was not allowed to use the inline type. Thats why I used the group type, which worked fine in 2.9.5. When trying to use the old group type again, the filebrowser is not showing any content.

![Bildschirmfoto 2023-08-28 um 13 23 10](https://github.com/a-r-m-i-n/dce/assets/10086856/0915ea4b-b759-4445-8223-997d123c159c)

Do you know how to use an image inside a section now?

Hope you can help. Thank you! Vincent

**Comment by a-r-m-i-n** [comment]
FAL (type: file) does not work inside of sections, and never did.
That the new record selector is unable to display sys_file records, seems to be also a core issue to me. 

You can bypass this, by updating TCA for sys_file, like this:
`$GLOBALS['TCA']['sys_file']['ctrl']['hideTable'] = 0;`

Then, the record selector shows sys_file records, as well as the list view on root level.

I told everyone, since years: Avoid using sections. Here you see, why.

**Comment by deg-hub** [comment]
I'm a little late to the party but a good workaround is to handle the given sys_file uids as simple typolinks to files, like an RTE link would do, so type file in flexform config should work accordingly and works kind of simple when you had a "maxtype" = 1 before.

All you need to do is migration to "file" in flexform-configuration of your DCE field, update the sys_file uid within the tt_content pi_flexform structure from
```
<field index="image">
    <value index="vDEF">123</value>
</field>
```
to
```
<field index="image">
    <value index="vDEF">t3://file?uid=123</value>
</field>
```

and handle the fluid output accordingly from something like
```<f:image image="{column.image.0}" />```
to
```<f:image src="{f:uri.typolink(parameter:column.image)}" />```

If you've used more than one sys_file item per field, migrating this way will be impossible while keeping backend UI fully functional, since file field does not support multiple values.
