### ISSUE TITLE
Using DCE-content in content-element "insert records" shows all DCE-content elements on the selected page

### ISSUE THREAD

**Issue by derBoogie** [a-r-m-i-n/dce#9]
I would like to show a subset of DCE-contents from another page on the home page.
Usually I use the content element "Insert record" for this purpose, but when I select DCE-content elements, It always shows all DCE-content elements from the selected page. It does not matter which DCE element(s) I select.

**Comment by a-r-m-i-n** [comment]
I'm sorry but I can't reconstruct this issue. I've tested with the latest DCE version in TYPO3 11 (with PHP 7.4).
I only get the selected content element.

Is it possible that you've got "Container" feature enabled for this DCE? Because there is an issue with that, which is also described in docs (in the Caution box): https://docs.typo3.org/p/t3/dce/main/en-us/UsersManual/DceContainer.html#enable-dce-container

**Comment by a-r-m-i-n** [comment]
No, unfortunately not. I also think, this is not trivial to fix.
In case there are some funds for investigating and developing existing, feel free to write me an email to info@v.ieweg.de :)
