### ISSUE TITLE
dce Migrate old files (type: group) to FAL (type: inline) - Upgrade Wizzard not working

### ISSUE THREAD

**Issue by akzeitlos** [a-r-m-i-n/dce#98]
**Versions**
- DCE version: newest
- TYPO3 version: **12**
- PHP version: **x.x**

**Describe the bug**
(1/1) RuntimeException
Unable to move media file from "/usr/www/users/princey/dev/public//fileadmin/user_upload/Inspirationen/baeder/640x480/amb-sunlight-cream-satin-vs-re.jpg" to "/usr/www/users/princey/dev/public/fileadmin///fileadmin/user_upload/Inspirationen/baeder/640x480/amb-sunlight-cream-satin-vs-re.jpg".

The paths are incorrect I think. Can you help?

**Comment by a-r-m-i-n** [comment]
I think the issue here is, that the script expects the files to be located outside of the fileadmin folder. Usually, files uploaded the old way were located in "uploads" directory, which is was a sibling of fileadmin.

Your files are already located in fileadmin.

What you could try is to create this upload directory, move all files in there and change the Flexform configuration "uploadfolder" from "/fileadmin/user_upload/" to "upload". Also, I suggest to get rid of trailing slashes at the beginning and ending in flexform config.

Then the migration should work.

**Comment by a-r-m-i-n** [comment]
Closing the issue, because of no response.
